# Generated by Django 6.0.2 on 2026-09-29 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prd_variant', '0005_alter_productsku_height_alter_productsku_length_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productsku',
            unique_together=set(),
        ),
    ]
