# Generated by Django 5.2.15 on 2026-06-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0031_alter_orderitem_height_alter_orderitem_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='discount_amt',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
