# Generated by Django 5.2.15 on 2026-06-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0032_orderitem_discount_amt'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
