# Generated by Django 6.0.2 on 2026-09-29 19:25

import django.db.models.deletion
from django.db import migrations, models


def backfill_sku_ids(apps, schema_editor):
    Item = apps.get_model('order', 'OrderItem')
    SKU = apps.get_model('prd_variant', 'ProductSKU')
    alias = schema_editor.connection.alias
    for item in Item.objects.using(alias).filter(sku__isnull=True).iterator():
        ids = list(SKU.objects.using(alias).filter(
            product_id=item.product_id, sku_code=item.sku_code).values_list('pk', flat=True)[:2])
        if len(ids) == 1:
            Item.objects.using(alias).filter(pk=item.pk).update(sku_id=ids[0])


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0036_mark_item_refunded_orders'),
        ('prd_variant', '0006_alter_productsku_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prd_variant.productsku'),
        ),
        migrations.RunPython(backfill_sku_ids, migrations.RunPython.noop),
    ]
