# Generated by Django 6.0.2 on 2026-06-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_upsconfig_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('publishable_key', models.CharField(blank=True, help_text='Stripe publishable key used by the frontend', max_length=255)),
                ('secret_key', models.CharField(blank=True, help_text='Stripe secret key used by the backend', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Stripe Config',
                'verbose_name_plural': 'Stripe Config',
            },
        ),
    ]
