# Generated by Django 6.0.2 on 2026-07-23 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_stripeconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxconfig',
            name='provider',
            field=models.CharField(choices=[('quickbooks', 'QuickBooks'), ('taxjar', 'TaxJar'), ('fallback', 'Fallback Table')], default='quickbooks', max_length=20),
        ),
    ]
