# Generated by Django 6.0.2 on 2026-09-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_add_show_in_gallery_to_blogpostimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagecontext',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
